---
sudo: required
services:
  - docker
branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/717f3329848ff6ab680f
      - https://api.opsgenie.com/v1/json/travisci?apiKey=38057e02-23ae-4ecc-b38f-a855cebc15eb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  - VERSION=jdk-7
  - VERSION=jdk-8
  - VERSION=jdk-8u45
  - VERSION=jdk-8u66
  - VERSION=jre-7
  - VERSION=jre-8
  - VERSION=jre-8u45
  - VERSION=jre-8u66
  - VERSION=serverjre-7
  - VERSION=serverjre-8
  - VERSION=serverjre-8u45
  - VERSION=serverjre-8u66
  - VERSION=latest

script:
- docker build -t scottmiller171/docker-java-bash:"$VERSION" ./"$VERSION"
- docker run -it scottmiller171/docker-java-bash:"$VERSION" ./"$VERSION" java -version
